//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 12.0.20617.1
// 
namespace WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectListItemWithClass", Namespace="http://schemas.datacontract.org/2004/07/UtilsShared")]
    public partial class SelectListItemWithClass : WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService.SelectListItem {
        
        private string ClassField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectListItem", Namespace="http://schemas.datacontract.org/2004/07/System.Web.Mvc")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService.SelectListItemWithClass))]
    public partial class SelectListItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool SelectedField;
        
        private string TextField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected {
            get {
                return this.SelectedField;
            }
            set {
                if ((this.SelectedField.Equals(value) != true)) {
                    this.SelectedField = value;
                    this.RaisePropertyChanged("Selected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BllProxy.EntityManagers.CategoryManagerService.ICategoryManager")]
    public interface ICategoryManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/GetAllForMenu", ReplyAction="http://tempuri.org/ICategoryManager/GetAllForMenuResponse")]
        System.Threading.Tasks.Task<string> GetAllForMenuAsync(string selected, System.Collections.ObjectModel.ObservableCollection<string> openedIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/GetAllSortedJson", ReplyAction="http://tempuri.org/ICategoryManager/GetAllSortedJsonResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService.SelectListItemWithClass>> GetAllSortedJsonAsync(System.Nullable<int> selectedCategoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryManager/GetCategoriesWithProductsInCategory", ReplyAction="http://tempuri.org/ICategoryManager/GetCategoriesWithProductsInCategoryResponse")]
        System.Threading.Tasks.Task<CommonPortable.Models.ProductModels.InCategoryCWPLVM> GetCategoriesWithProductsInCategoryAsync(int pageNumber, int productsPerPage, string baseCategoryFu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoryManagerChannel : WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService.ICategoryManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryManagerClient : System.ServiceModel.ClientBase<WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService.ICategoryManager>, WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService.ICategoryManager {
        
        public CategoryManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<string> GetAllForMenuAsync(string selected, System.Collections.ObjectModel.ObservableCollection<string> openedIds) {
            return base.Channel.GetAllForMenuAsync(selected, openedIds);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<WinStoreClientProxy.BllProxy.EntityManagers.CategoryManagerService.SelectListItemWithClass>> GetAllSortedJsonAsync(System.Nullable<int> selectedCategoryId) {
            return base.Channel.GetAllSortedJsonAsync(selectedCategoryId);
        }
        
        public System.Threading.Tasks.Task<CommonPortable.Models.ProductModels.InCategoryCWPLVM> GetCategoriesWithProductsInCategoryAsync(int pageNumber, int productsPerPage, string baseCategoryFu) {
            return base.Channel.GetCategoriesWithProductsInCategoryAsync(pageNumber, productsPerPage, baseCategoryFu);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
